"use client";

import { useMemo, useState } from "react";
import { PARTIES, baselinesFromPolls, colorOf, formatList, pollWeights, weightedBaselineFromPolls, type BaselineKey, type Party, type Poll, type VoteMap } from "./model";
import { POLL_SOURCE_URL } from "./poll-refresh";
import { PartyPortraits } from "./party-portraits";
import { formatDate, formatNumber, localeOf, otherLabel, translate, type Language } from "./i18n";

const pollKey = (poll: Poll) => `${poll.date}|${poll.firm}|${poll.n}`;
const MAJORS: Party[] = ["HDZ", "SDP", "Mozemo", "Most", "DP"];

export function PollEvidence({ language, polls, baseline, onBaseline, raw, national, hasAdjustments }: { language: Language; polls: Poll[]; baseline: BaselineKey; onBaseline: (key: BaselineKey)=>void; raw: VoteMap; national: VoteMap; hasAdjustments: boolean }) {
  const t = (hr: string, de: string, en?: string) => translate(language, hr, de, en);
  const sources = useMemo(()=>baselinesFromPolls(polls),[polls]);
  const source = sources[baseline] ?? sources.weighted;
  const rows = pollWeights(source.polls);
  const weights = new Map(rows.map(row=>[pollKey(row.poll),row]));
  const [allRows,setAllRows] = useState(false);
  const [allParties,setAllParties] = useState(false);
  const [party,setParty] = useState<Party>("Mozemo");
  const visiblePolls = allRows ? polls : source.polls;
  const tableParties = allParties ? PARTIES : MAJORS;
  const sourceMean = source.vals[party];
  return <div className="poll-evidence">
    <div className="section-heading"><div><p className="section-kicker">{t("Podaci iza modela", "Datengrundlage des Modells")}</p><h1>{t("Ankete i trendovi", "Umfragen und Trends")}</h1><p>{polls.length} {t("upotrebljivih anketa", "verwendbare Umfragen")} · {formatDate(polls.at(-1)!.date, language)} – {formatDate(polls[0].date, language)}</p></div><a className="secondary-button" href={POLL_SOURCE_URL+"#Opinion_polls"} target="_blank" rel="noreferrer">{t("Tablica anketa na Wikipediji ↗", "Wikipedia-Umfragetabelle ↗")}</a></div>
    <div className="source-cards">{(["weighted","ipsos","promocija"] as const).map(key=>{
      const item = sources[key]; if (!item) return null;
      return <button type="button" key={key} className={`source-card ${key===baseline?"active":""}`} aria-pressed={key===baseline} onClick={()=>onBaseline(key)}><span>{key==="weighted"?t("Ponderirani prosjek", "Gewichteter Durchschnitt"):key==="ipsos"?t("Samo najnoviji Ipsos", "Nur neueste Ipsos-Umfrage"):t("Samo najnovija Promocija Plus", "Nur neueste Promocija-Plus-Umfrage")}</span><strong>{key==="weighted"?t("10 nedavnih anketa", "10 jüngste Umfragen"):formatDate(item.polls[0].date, language)}</strong><small>{key==="weighted"?t("Aktualnost + veličina uzorka", "Aktualität + Stichprobengröße"):t("100% težine ovoj anketi", "100% Gewicht für diese Umfrage")}</small></button>;
    })}</div>
    <PollTrend language={language} polls={polls}/>
    <section className="card weighting-card">
      <div className="section-heading"><div><h2>{t("Od objavljenih podataka do scenarija", "Von veröffentlichten Werten zum Szenario")}</h2><p>{hasAdjustments?t("Aktivne su vaše prilagodbe stranaka.", "Ihre Parteianpassungen sind aktiv."):t("Scenarij počinje od odabranog izvora anketa.", "Das Szenario beginnt mit der ausgewählten Umfragequelle.")}</p></div><label className="inline-control">{t("Pregledaj stranku", "Partei prüfen")}<select value={party} onChange={event=>setParty(event.target.value as Party)}>{PARTIES.map(p=><option key={p} value={p}>{otherLabel(formatList(p), language)}</option>)}</select></label></div>
      <div className="calculation-steps">
        <div><span>{t("Odabrani izvor", "Ausgewählte Quelle")}</span><strong>{formatNumber(sourceMean, language, 2)}%</strong><small>{otherLabel(formatList(party), language)} · {t("sirovo, uključuje neodlučne", "roh, einschließlich Unentschlossener")}</small></div>
        <div><span>{t("Ulaz scenarija", "Szenarioeingabe")}</span><strong>{formatNumber(raw[party], language, 2)}%</strong><small>{Math.abs(raw[party]-sourceMean)>0.001?t(`${raw[party]-sourceMean>=0?"+":""}${formatNumber(raw[party]-sourceMean, language, 2)} boda ručne prilagodbe`, `${raw[party]-sourceMean>=0?"+":""}${formatNumber(raw[party]-sourceMean, language, 2)} Punkte manuell angepasst`, `${raw[party]-sourceMean>=0?"+":""}${formatNumber(raw[party]-sourceMean, language, 2)} points manually adjusted`):t("Nema ručne prilagodbe stranke", "Keine manuelle Parteianpassung")}</small></div>
        <div><span>{t("Efektivni nacionalni udio", "Effektiver Landesanteil")}</span><strong>{formatNumber(national[party], language, 2)}%</strong><small>{t("Nakon normalizacije i raspodjele neodlučnih", "Nach Normierung und Verteilung der Unentschlossenen")}</small></div>
      </div>
      <details className="weight-method" open><summary>{t("Točno ponderiranje i pretpostavke", "Genaue Gewichtung und Annahmen")}</summary><p>{baseline==="weighted"?t("Svaka od deset najnovijih anketa dobiva težinu √veličine uzorka × exp(−starost u danima / 60). Njezin doprinos dobiva se dijeljenjem sa zbrojem svih težina. Starost se mjeri od najnovije uključene ankete. Anketa starija 60 dana zadržava 36,8% težine aktualnosti; dvostruko veći uzorak množi težinu s 1,414. Ne primjenjuje se korekcija za anketnu kuću.", "Jede der zehn neuesten Umfragen erhält das Gewicht √Stichprobengröße × exp(−Alter in Tagen / 60). Ihr Beitrag ergibt sich durch Division durch die Summe aller Gewichte. Das Alter wird ab der neuesten einbezogenen Umfrage gemessen. Eine 60 Tage ältere Umfrage behält 36,8% ihres Aktualitätsgewichts; eine doppelte Stichprobe multipliziert das Gewicht mit 1,414. Es gibt keine Korrektur nach Institut."):t("Odabrana anketa pridonosi 100%. Ostale ankete imaju nultu težinu. Njezini objavljeni udjeli i broj neodlučnih zamjenjuju prosjek; profili izbornih jedinica i ostale postavke scenarija i dalje se primjenjuju.", "Die ausgewählte Umfrage trägt 100% bei. Andere Umfragen haben Gewicht null. Ihre veröffentlichten Anteile und der Wert der Unentschlossenen ersetzen den Durchschnitt; Wahlkreisprofile und weitere Szenarioeinstellungen gelten weiterhin.")}</p><p>{t("Crtica na Wikipediji znači da vrijednost nije objavljena ili je ispod praga izvještavanja, a ne izmjerenu nulu. Te ćelije ovdje su označene s „—”. Naslijeđeni model pretpostavlja 0,5% za neprijavljenu stranku i 0,4% za HSP, koji nema zaseban stupac. Pretpostavke ulaze u prosjek, ali ne i u sirove točke grafikona. „Ostali” se usklađuju s ukupnim brojem opredijeljenih prije raspodjele. Efektivni nacionalni udjeli prethode gubicima birača koalicija.", "Ein Strich bei Wikipedia bedeutet nicht gemeldet oder unterhalb der Berichtsgrenze, nicht gemessene null. Diese Zellen erscheinen hier als „—”. Das übernommene Modell setzt 0,5% für eine nicht gemeldete Partei und 0,4% für HSP an, für die es keine eigene Spalte gibt. Annahmen fließen in den Durchschnitt ein, werden aber als rohe Diagrammpunkte ausgelassen. „Sonstige” werden vor der Verteilung an die Summe der Entschiedenen angeglichen. Effektive Landesanteile werden vor Koalitionsverlusten berechnet.")}</p></details>
    </section>
    <section className="card poll-table-card">
      <div className="section-heading"><div><h2>{allRows?t("Povijest anketa", "Umfrageverlauf"):t("Ankete korištene u ovoj osnovici", "In dieser Basis verwendete Umfragen")}</h2><p>{baseline==="weighted"?t("Ponderirani prosjek", "Gewichteter Durchschnitt"):source.polls[0]?.firm} · {source.polls.length} {t("uključenih anketa", "einbezogene Umfragen")}</p></div><div className="table-options"><label><input type="checkbox" checked={allRows} onChange={e=>setAllRows(e.target.checked)}/>{t("Svi povijesni redci", "Alle historischen Zeilen")}</label><label><input type="checkbox" checked={allParties} onChange={e=>setAllParties(e.target.checked)}/>{t("Sve stranke", "Alle Parteien")}</label></div></div>
      <div className="table-scroll" tabIndex={0} role="region" aria-label={t("Rezultati anketa i točne težine; pomaknite vodoravno za dodatne stupce", "Umfragewerte und genaue Gewichtung; für weitere Spalten horizontal scrollen")}><table className="poll-data-table"><caption>{t("Udjeli su postotci svih ispitanika. Težina je doprinos ankete odabranoj osnovici.", "Anteile sind Prozentsätze aller Befragten. Das Gewicht ist der Beitrag der Umfrage zur ausgewählten Basis.")}</caption><thead><tr><th>{t("Datum / izvor", "Datum / Quelle")}</th><th>{t("Anketna kuća", "Institut")}</th><th>{t("Uzorak", "Stichprobe")}</th>{tableParties.map(p=><th key={p}>{otherLabel(formatList(p), language)}</th>)}<th>{t("Neodlučni", "Unentschlossen")}</th><th>{t("Starost (dani)", "Alter (Tage)")}</th><th>{t("Aktualnost", "Aktualität")}</th><th>{t("√uzorka", "√Stichprobe")}</th><th>{t("Težina", "Gewicht")}</th></tr></thead><tbody>{visiblePolls.map(poll=>{
        const row=weights.get(pollKey(poll));return <tr key={pollKey(poll)} className={row?"included":""}><th><a href={poll.sourceUrl??POLL_SOURCE_URL} target="_blank" rel="noreferrer">{formatDate(poll.date, language)} ↗</a></th><td>{poll.firm}</td><td>{poll.n.toLocaleString(localeOf(language))}</td>{tableParties.map(p=><td key={p}>{poll.imputed?.includes(p)?<span className="missing-figure" title={t(`Nije objavljeno; model pretpostavlja ${formatNumber(poll.v[p], language, 1)}%`, `Nicht gemeldet; Modell setzt ${formatNumber(poll.v[p], language, 1)}% an`, `Unreported; model assumes ${formatNumber(poll.v[p], language, 1)}%`)}>—</span>:formatNumber(poll.v[p], language, 1)}</td>)}<td>{formatNumber(poll.und, language, 1)}</td><td>{row?formatNumber(row.ageDays, language, 0):"—"}</td><td>{row?(baseline==="weighted"?formatNumber(row.recency, language, 4):formatNumber(1, language, 4)):"—"}</td><td>{row?(baseline==="weighted"?formatNumber(row.sampleWeight, language, 3):"—"):"—"}</td><td><strong>{row?formatNumber(row.normalizedWeight*100, language, 2)+"%":"0%"}</strong></td></tr>;
      })}<tr className="average-row"><th colSpan={3}>{t("Prosjek odabranog izvora", "Durchschnitt der ausgewählten Quelle")}</th>{tableParties.map(p=><td key={p}>{formatNumber(source.vals[p], language, 2)}</td>)}<td>{formatNumber(source.und, language, 2)}</td><td colSpan={3}>{t("Uključene pretpostavke za neobjavljene stranke", "Annahmen für nicht gemeldete Parteien enthalten")}</td><td>100%</td></tr></tbody></table></div>
      <p className="panel-footnote">{t("Isključeni su povijesni redci bez upotrebljivog uzorka, udjela neodlučnih ili rezultata glavnih stranaka. Ankete vode na izvještaje o rezultatima koje navodi Wikipedia.", "Historische Zeilen ohne verwendbare Stichprobe, Wert der Unentschlossenen oder Ergebnisse der großen Parteien sind ausgeschlossen. Die Umfragen verlinken auf die von Wikipedia genannten Ergebnisberichte.")}</p>
    </section>
  </div>;
}

function PollTrend({language,polls}:{language:Language;polls:Poll[]}) {
  const t = (hr: string, de: string, en?: string) => translate(language, hr, de, en);
  const [parties,setParties] = useState<Party[]>(["HDZ","SDP","Mozemo","Most"]);
  const [firm,setFirm] = useState("all");
  const [range,setRange] = useState("all");
  const [display,setDisplay] = useState<"weighted"|"raw">("weighted");
  const [selectedKey,setSelectedKey] = useState("");
  const history = useMemo(()=>{
    const chronological=[...polls].filter(p=>firm==="all"||p.firm===firm).sort((a,b)=>a.date.localeCompare(b.date));
    return chronological.map((poll,index)=>({poll,trend:weightedBaselineFromPolls(chronological.slice(Math.max(0,index-9),index+1)).vals,count:Math.min(10,index+1)}));
  },[polls,firm]);
  const cutoff = new Date(polls[0].date).getTime() - (range==="6m"?183:365)*86400000;
  const shown = history.filter(({poll})=>range==="all"||new Date(poll.date).getTime()>=cutoff);
  const selectedIndex = Math.max(0,shown.findIndex(({poll})=>pollKey(poll)===selectedKey));
  const activeIndex=selectedKey&&shown.some(({poll})=>pollKey(poll)===selectedKey)?selectedIndex:shown.length-1;
  const active=shown[activeIndex];
  const width=1100,height=335,left=54,right=24,top=16,bottom=42;
  const first=new Date(shown[0]?.poll.date??polls[0].date).getTime(),last=new Date(shown.at(-1)?.poll.date??polls[0].date).getTime();
  const maximum=Math.max(5,Math.ceil(Math.max(...shown.flatMap(row=>parties.map(p=>Math.max(row.trend[p],row.poll.imputed?.includes(p)?0:row.poll.v[p]))))/5)*5);
  const x=(poll:Poll)=>left+(new Date(poll.date).getTime()-first)/Math.max(1,last-first)*(width-left-right);
  const y=(value:number)=>top+(1-value/maximum)*(height-top-bottom);
  const ticks=Array.from({length:6},(_,i)=>maximum*i/5);
  const toggle=(p:Party)=>setParties(current=>current.includes(p)?current.length===1?current:current.filter(item=>item!==p):[...current,p]);
  return <section className="card trends-card">
    <div className="section-heading"><div><h2>{t("Ankete kroz vrijeme", "Umfragen im Zeitverlauf")}</h2><p>{t("Sirovi udjeli uključuju neodlučne", "Rohe Anteile einschließlich Unentschlossener")} · {display==="weighted"?t("linija = pomični ponderirani prosjek; točke = objavljene ankete", "Linie = gleitender gewichteter Durchschnitt; Punkte = veröffentlichte Umfragen"):t("točke = objavljene ankete", "Punkte = veröffentlichte Umfragen")}.</p></div><div className="chart-filters"><label>{t("Anketne kuće", "Institute")}<select value={firm} onChange={e=>{setFirm(e.target.value);setSelectedKey("")}}><option value="all">{t("Sve anketne kuće", "Alle Institute")}</option>{[...new Set(polls.map(p=>p.firm))].map(f=><option key={f}>{f}</option>)}</select></label><label>{t("Razdoblje", "Zeitraum")}<select value={range} onChange={e=>{setRange(e.target.value);setSelectedKey("")}}><option value="all">{t("Od travnja 2024.", "Seit April 2024")}</option><option value="1y">{t("Zadnjih 12 mjeseci", "Letzte 12 Monate")}</option><option value="6m">{t("Zadnjih 6 mjeseci", "Letzte 6 Monate")}</option></select></label><label>{t("Prikaz", "Anzeige")}<select value={display} onChange={e=>setDisplay(e.target.value as "raw"|"weighted")}><option value="weighted">{t("Ponderirani trend", "Gewichteter Trend")}</option><option value="raw">{t("Objavljene ankete", "Veröffentlichte Umfragen")}</option></select></label></div></div>
    <div className="chart-legend">{Array.from(new Set([...MAJORS,...parties])).map(p=><button type="button" key={p} className={parties.includes(p)?"active":""} aria-pressed={parties.includes(p)} onClick={()=>toggle(p)}><PartyPortraits name={p}/><i style={{background:colorOf(p)}}/>{otherLabel(formatList(p), language)}</button>)}<label className="add-series"><span>{t("Dodaj stranku", "Partei hinzufügen")}</span><select value="" onChange={e=>{if(e.target.value)setParties(current=>[...current,e.target.value as Party])}}><option value="">{t("Odaberi…", "Auswählen…")}</option>{PARTIES.filter(p=>!parties.includes(p)&&!MAJORS.includes(p)).map(p=><option key={p} value={p}>{otherLabel(formatList(p), language)}</option>)}</select></label></div>
    {shown.length > 0 ? <div className="trend-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={t(`Povijesni sirovi anketni udjeli i ponderirani trendovi za ${parties.map(formatList).join(", ")}. Točne vrijednosti mogu se pregledati ispod.`, `Historische rohe Umfrageanteile und gewichtete Trends für ${parties.map(formatList).join(", ")}. Genaue Werte können unten geprüft werden.`, `Historical raw poll shares and weighted trends for ${parties.map(formatList).join(", ")}. Exact values can be inspected below.`)} onPointerMove={event=>{const bounds=event.currentTarget.getBoundingClientRect();const scale=Math.min(bounds.width/width,bounds.height/height);const at=(event.clientX-bounds.left-(bounds.width-width*scale)/2)/scale;const nearest=shown.reduce((best,row)=>Math.abs(x(row.poll)-at)<Math.abs(x(best.poll)-at)?row:best,shown[0]);setSelectedKey(pollKey(nearest.poll))}}>
      {ticks.map(t=><g key={t}><line x1={left} x2={width-right} y1={y(t)} y2={y(t)} className="chart-grid"/><text x={left-12} y={y(t)+5} textAnchor="end">{t.toFixed(0)}%</text></g>)}
      {Array.from({length:5},(_,i)=>Math.round(i*(shown.length-1)/4)).filter((n,i,a)=>a.indexOf(n)===i).map(i=><text key={i} x={x(shown[i].poll)} y={height-12} textAnchor={i===0?"start":i===shown.length-1?"end":"middle"}>{formatDate(shown[i].poll.date, language, true)}</text>)}
      {parties.map(p=><g key={p}>{display==="weighted"&&<path d={shown.map((row,i)=>`${i?"L":"M"}${x(row.poll).toFixed(1)} ${y(row.trend[p]).toFixed(1)}`).join(" ")} fill="none" stroke={colorOf(p)} strokeWidth="3" strokeLinejoin="round"/>}{shown.filter(({poll})=>!poll.imputed?.includes(p)).map(({poll})=><circle key={pollKey(poll)} cx={x(poll)} cy={y(poll.v[p])} r={display==="raw"?4:2.8} fill={colorOf(p)} opacity={display==="raw"?0.9:0.45}><title>{formatDate(poll.date, language)} · {poll.firm} · {otherLabel(formatList(p), language)} {formatNumber(poll.v[p], language, 1)}%</title></circle>)}</g>)}
      {active&&<line x1={x(active.poll)} x2={x(active.poll)} y1={top} y2={height-bottom} className="chart-cursor"/>}
    </svg></div> : <p className="empty-chart">{t("Nema anketa ove kuće u odabranom razdoblju. Odaberite dulje razdoblje ili sve kuće.", "Für dieses Institut gibt es im gewählten Zeitraum keine Umfragen. Wählen Sie einen längeren Zeitraum oder alle Institute.")}</p>}
    {active&&<div className="trend-inspector"><label htmlFor="trend-date">{t("Pregledaj anketu", "Umfrage prüfen")} <b>{formatDate(active.poll.date, language)} · {active.poll.firm}</b></label><input id="trend-date" type="range" min="0" max={shown.length-1} step="1" value={activeIndex} onChange={e=>setSelectedKey(pollKey(shown[Number(e.target.value)].poll))} aria-valuetext={formatDate(active.poll.date, language)+" "+active.poll.firm}/><div className="trend-values">{parties.map(p=><span key={p}><i className="swatch" style={{background:colorOf(p)}}/>{otherLabel(formatList(p), language)} <b>{display==="weighted"?formatNumber(active.trend[p], language, 2)+"%":active.poll.imputed?.includes(p)?"—":formatNumber(active.poll.v[p], language, 1)+"%"}</b></span>)}</div><small>{display==="weighted"?t(`Pomični prosjek ${active.count} anketa dostupnih do ovog datuma unutar odabranog filtra anketnih kuća. Buduće ankete nisu korištene.`, `Gleitender Durchschnitt aus ${active.count} bis zu diesem Datum verfügbaren Umfragen innerhalb des gewählten Institutsfilters. Zukünftige Umfragen werden nicht verwendet.`, `Trailing average of ${active.count} polls available by this date, within the selected pollster filter. No future polls are used.`):t("Samo objavljene vrijednosti. Neobjavljene vrijednosti prikazane su kao praznine.", "Nur veröffentlichte Werte. Nicht gemeldete Werte erscheinen als Lücken.")} {t("Grafikon ne uključuje vaše prilagodbe scenarija.", "Das Diagramm enthält Ihre Szenarioanpassungen nicht.")}</small></div>}
  </section>;
}
